// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game.proto
// Protobuf C++ Version: 5.29.5

#include "game.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace gamepackage {

inline constexpr StartRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : playermoney_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR StartRequest::StartRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct StartRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StartRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StartRequestDefaultTypeInternal() {}
  union {
    StartRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StartRequestDefaultTypeInternal _StartRequest_default_instance_;

inline constexpr CountDownSync::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : countdown_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CountDownSync::CountDownSync(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CountDownSyncDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CountDownSyncDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CountDownSyncDefaultTypeInternal() {}
  union {
    CountDownSync _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CountDownSyncDefaultTypeInternal _CountDownSync_default_instance_;
}  // namespace gamepackage
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_game_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_game_2eproto = nullptr;
const ::uint32_t
    TableStruct_game_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gamepackage::StartRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gamepackage::StartRequest, _impl_.playermoney_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::gamepackage::CountDownSync, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::gamepackage::CountDownSync, _impl_.countdown_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::gamepackage::StartRequest)},
        {9, -1, -1, sizeof(::gamepackage::CountDownSync)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::gamepackage::_StartRequest_default_instance_._instance,
    &::gamepackage::_CountDownSync_default_instance_._instance,
};
const char descriptor_table_protodef_game_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\ngame.proto\022\013gamepackage\"#\n\014StartReques"
    "t\022\023\n\013playermoney\030\001 \001(\005\"\"\n\rCountDownSync\022"
    "\021\n\tcountdown\030\001 \001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_game_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_game_2eproto = {
    false,
    false,
    106,
    descriptor_table_protodef_game_2eproto,
    "game.proto",
    &descriptor_table_game_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_game_2eproto::offsets,
    file_level_enum_descriptors_game_2eproto,
    file_level_service_descriptors_game_2eproto,
};
namespace gamepackage {
// ===================================================================

class StartRequest::_Internal {
 public:
};

StartRequest::StartRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gamepackage.StartRequest)
}
StartRequest::StartRequest(
    ::google::protobuf::Arena* arena, const StartRequest& from)
    : StartRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE StartRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void StartRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.playermoney_ = {};
}
StartRequest::~StartRequest() {
  // @@protoc_insertion_point(destructor:gamepackage.StartRequest)
  SharedDtor(*this);
}
inline void StartRequest::SharedDtor(MessageLite& self) {
  StartRequest& this_ = static_cast<StartRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* StartRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) StartRequest(arena);
}
constexpr auto StartRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(StartRequest),
                                            alignof(StartRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull StartRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_StartRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &StartRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<StartRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &StartRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<StartRequest>(), &StartRequest::ByteSizeLong,
            &StartRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(StartRequest, _impl_._cached_size_),
        false,
    },
    &StartRequest::kDescriptorMethods,
    &descriptor_table_game_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* StartRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> StartRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gamepackage::StartRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 playermoney = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(StartRequest, _impl_.playermoney_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(StartRequest, _impl_.playermoney_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 playermoney = 1;
    {PROTOBUF_FIELD_OFFSET(StartRequest, _impl_.playermoney_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void StartRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:gamepackage.StartRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.playermoney_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* StartRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const StartRequest& this_ = static_cast<const StartRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* StartRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const StartRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:gamepackage.StartRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 playermoney = 1;
          if (this_._internal_playermoney() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_playermoney(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:gamepackage.StartRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t StartRequest::ByteSizeLong(const MessageLite& base) {
          const StartRequest& this_ = static_cast<const StartRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t StartRequest::ByteSizeLong() const {
          const StartRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:gamepackage.StartRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 playermoney = 1;
            if (this_._internal_playermoney() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_playermoney());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void StartRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<StartRequest*>(&to_msg);
  auto& from = static_cast<const StartRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gamepackage.StartRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_playermoney() != 0) {
    _this->_impl_.playermoney_ = from._impl_.playermoney_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void StartRequest::CopyFrom(const StartRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gamepackage.StartRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StartRequest::InternalSwap(StartRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.playermoney_, other->_impl_.playermoney_);
}

::google::protobuf::Metadata StartRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CountDownSync::_Internal {
 public:
};

CountDownSync::CountDownSync(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:gamepackage.CountDownSync)
}
CountDownSync::CountDownSync(
    ::google::protobuf::Arena* arena, const CountDownSync& from)
    : CountDownSync(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE CountDownSync::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CountDownSync::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.countdown_ = {};
}
CountDownSync::~CountDownSync() {
  // @@protoc_insertion_point(destructor:gamepackage.CountDownSync)
  SharedDtor(*this);
}
inline void CountDownSync::SharedDtor(MessageLite& self) {
  CountDownSync& this_ = static_cast<CountDownSync&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* CountDownSync::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CountDownSync(arena);
}
constexpr auto CountDownSync::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CountDownSync),
                                            alignof(CountDownSync));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CountDownSync::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CountDownSync_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CountDownSync::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CountDownSync>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CountDownSync::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CountDownSync>(), &CountDownSync::ByteSizeLong,
            &CountDownSync::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CountDownSync, _impl_._cached_size_),
        false,
    },
    &CountDownSync::kDescriptorMethods,
    &descriptor_table_game_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CountDownSync::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> CountDownSync::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::gamepackage::CountDownSync>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 countdown = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CountDownSync, _impl_.countdown_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CountDownSync, _impl_.countdown_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 countdown = 1;
    {PROTOBUF_FIELD_OFFSET(CountDownSync, _impl_.countdown_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void CountDownSync::Clear() {
// @@protoc_insertion_point(message_clear_start:gamepackage.CountDownSync)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.countdown_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CountDownSync::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CountDownSync& this_ = static_cast<const CountDownSync&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CountDownSync::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CountDownSync& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:gamepackage.CountDownSync)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 countdown = 1;
          if (this_._internal_countdown() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_countdown(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:gamepackage.CountDownSync)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CountDownSync::ByteSizeLong(const MessageLite& base) {
          const CountDownSync& this_ = static_cast<const CountDownSync&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CountDownSync::ByteSizeLong() const {
          const CountDownSync& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:gamepackage.CountDownSync)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // int32 countdown = 1;
            if (this_._internal_countdown() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_countdown());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CountDownSync::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CountDownSync*>(&to_msg);
  auto& from = static_cast<const CountDownSync&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:gamepackage.CountDownSync)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_countdown() != 0) {
    _this->_impl_.countdown_ = from._impl_.countdown_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CountDownSync::CopyFrom(const CountDownSync& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gamepackage.CountDownSync)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CountDownSync::InternalSwap(CountDownSync* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.countdown_, other->_impl_.countdown_);
}

::google::protobuf::Metadata CountDownSync::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace gamepackage
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_game_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
